name: Release

on: { push: { tags: '[0-9]+.[0-9]+.[0-9]+*' } }

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: { contents: write } # for creating a GitHub release
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun i

      - name: Build
        run: bun build:prod

      - name: Lint
        run: bun lint

      - name: Create release archive
        run: |
          ARCHIVE_NAME=${GITHUB_REPOSITORY##*/}-$TAG.zip
          echo ARCHIVE_NAME=$ARCHIVE_NAME >> $GITHUB_ENV
          zip -r $ARCHIVE_NAME manifest.json main.js styles.css

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $TAG --title $TAG --draft \
          manifest.json main.js styles.css $ARCHIVE_NAME